name: "Publish to NPM"

on:
    push:
        branches:
          - master

jobs:
    release:
        name: Job - Compile unbuilt TS files and publish to NPM
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1
            - name: Install Node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
              env:
                ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
            - name: Install NPM Packages
              run: npm install
            - name: Building Typescript
              uses: FuLagann/tsc-build-push@v1
              with:
                user-name: "Cristian F. Shute"
                user-email: "chris_fs313@hotmail.com"
                message: "Automatically built unbuilt typescript"
                directories: ./
            - name: Publish to NPM
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}